runtime: python37
entrypoint: gunicorn -b :$PORT main:app --timeout 1800
#runtime: custom
#env: flex

instance_class: B4_HIGHMEM
basic_scaling:
  max_instances: 11
  idle_timeout: 10m


env_variables:
    CLOUD_STORAGE_BUCKET: art-retrieval-api-234614.appspot.com

handlers:
  
- url: /.*
  script: auto
